// <auto-generated />
using System;
using Doario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doario.Data.Migrations
{
    [DbContext(typeof(DoarioDataContext))]
    partial class DoarioDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Doario.Data.Models.Lookups.AssignmentType", b =>
                {
                    b.Property<int>("AssignmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("AssignmentTypeId");

                    b.ToTable("AssignmentTypes");

                    b.HasData(
                        new
                        {
                            AssignmentTypeId = 1,
                            Name = "Primary",
                            SortOrder = 100
                        },
                        new
                        {
                            AssignmentTypeId = 2,
                            Name = "CC",
                            SortOrder = 200
                        });
                });

            modelBuilder.Entity("Doario.Data.Models.Lookups.DocumentStatus", b =>
                {
                    b.Property<int>("DocumentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentStatusId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentStatusId");

                    b.ToTable("DocumentStatuses");

                    b.HasData(
                        new
                        {
                            DocumentStatusId = 1,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Unassigned",
                            SortOrder = 100,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DocumentStatusId = 2,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Assigned",
                            SortOrder = 200,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DocumentStatusId = 3,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Read",
                            SortOrder = 300,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DocumentStatusId = 4,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Actioned",
                            SortOrder = 400,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Doario.Data.Models.Lookups.MessageType", b =>
                {
                    b.Property<int>("MessageTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("MessageTypeId");

                    b.ToTable("MessageTypes");

                    b.HasData(
                        new
                        {
                            MessageTypeId = 1,
                            Name = "Note",
                            SortOrder = 100
                        },
                        new
                        {
                            MessageTypeId = 2,
                            Name = "ActionedViaOutlook",
                            SortOrder = 200
                        },
                        new
                        {
                            MessageTypeId = 3,
                            Name = "ActionedViaPortal",
                            SortOrder = 300
                        },
                        new
                        {
                            MessageTypeId = 4,
                            Name = "Forwarded",
                            SortOrder = 400
                        },
                        new
                        {
                            MessageTypeId = 5,
                            Name = "AdminConfirmedViaOutlook",
                            SortOrder = 500
                        },
                        new
                        {
                            MessageTypeId = 6,
                            Name = "AdminReassignedViaOutlook",
                            SortOrder = 600
                        },
                        new
                        {
                            MessageTypeId = 7,
                            Name = "AdminMarkedUrgent",
                            SortOrder = 700
                        },
                        new
                        {
                            MessageTypeId = 8,
                            Name = "ViewedDocument",
                            SortOrder = 800
                        });
                });

            modelBuilder.Entity("Doario.Data.Models.Lookups.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeId = 1,
                            Name = "NewDocument",
                            SortOrder = 100
                        },
                        new
                        {
                            NotificationTypeId = 2,
                            Name = "Urgent",
                            SortOrder = 200
                        },
                        new
                        {
                            NotificationTypeId = 3,
                            Name = "Forwarded",
                            SortOrder = 300
                        },
                        new
                        {
                            NotificationTypeId = 4,
                            Name = "MessageReceived",
                            SortOrder = 400
                        });
                });

            modelBuilder.Entity("Doario.Data.Models.Lookups.Sender", b =>
                {
                    b.Property<Guid>("SenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SenderTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SenderId");

                    b.HasIndex("SenderTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("Senders");
                });

            modelBuilder.Entity("Doario.Data.Models.Lookups.SenderType", b =>
                {
                    b.Property<Guid>("SenderTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayNameColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmailContentLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TableName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SenderTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("SenderTypes");
                });

            modelBuilder.Entity("Doario.Data.Models.Lookups.SourceType", b =>
                {
                    b.Property<int>("SourceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SourceTypeId");

                    b.ToTable("SourceTypes");

                    b.HasData(
                        new
                        {
                            SourceTypeId = 1,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CSV",
                            SortOrder = 100,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SourceTypeId = 2,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "MicrosoftGraph",
                            SortOrder = 200,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SourceTypeId = 3,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GoogleDirectory",
                            SortOrder = 300,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SourceTypeId = 4,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Connector",
                            SortOrder = 400,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SourceTypeId = 5,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "SalesforceAPI",
                            SortOrder = 500,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SourceTypeId = 6,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PowerSchoolAPI",
                            SortOrder = 600,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SourceTypeId = 7,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CustomDatabase",
                            SortOrder = 700,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SourceTypeId = 8,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CustomAPI",
                            SortOrder = 800,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SourceTypeId = 9,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "VirtualMailroom",
                            SortOrder = 900,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Doario.Data.Models.Lookups.SystemStatus", b =>
                {
                    b.Property<int>("SystemStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemStatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SystemStatusId");

                    b.ToTable("SystemStatuses");

                    b.HasData(
                        new
                        {
                            SystemStatusId = 1,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Active",
                            SortOrder = 100,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SystemStatusId = 2,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Expired",
                            SortOrder = 200,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SystemStatusId = 3,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Revoked",
                            SortOrder = 300,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SystemStatusId = 4,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Success",
                            SortOrder = 400,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SystemStatusId = 5,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Failed",
                            SortOrder = 500,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SystemStatusId = 6,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PartialSuccess",
                            SortOrder = 600,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SystemStatusId = 7,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pending",
                            SortOrder = 700,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            SystemStatusId = 8,
                            EndDate = new DateTime(9999, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sent",
                            SortOrder = 800,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("OcrText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SenderMatchConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("SenderTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SharePointUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentId");

                    b.HasIndex("DocumentStatusId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SenderTypeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UploadedByStaffId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.DocumentAssignment", b =>
                {
                    b.Property<Guid>("DocumentAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AIConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("AIConfirmedByAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("AISuggestedEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AdminAccessToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("AdminAccessTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AssignedByAI")
                        .HasColumnType("bit");

                    b.Property<Guid>("AssignedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedToEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("AssignedToStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssignmentTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StaffAccessToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StaffAccessTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentAssignmentId");

                    b.HasIndex("AssignedToStaffId");

                    b.HasIndex("AssignmentTypeId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("TenantId");

                    b.ToTable("DocumentAssignments");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.DocumentDelivery", b =>
                {
                    b.Property<Guid>("DocumentDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SentToEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SystemStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentDeliveryId");

                    b.HasIndex("DocumentAssignmentId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SystemStatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("DocumentDeliveries");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.DocumentMessage", b =>
                {
                    b.Property<Guid>("DocumentMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MessageTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentMessageId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("MessageTypeId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TenantId");

                    b.ToTable("DocumentMessages");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.ImportedSender", b =>
                {
                    b.Property<Guid>("ImportedSenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SenderTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImportedSenderId");

                    b.HasIndex("SenderTypeId");

                    b.HasIndex("SourceTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("ImportedSenders");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.ImportedStaff", b =>
                {
                    b.Property<Guid>("ImportedStaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdminOverridden")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfficeLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImportedStaffId");

                    b.HasIndex("SourceTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("ImportedStaff", (string)null);
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.DocumentUsage", b =>
                {
                    b.Property<Guid>("DocumentUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveStaffCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BilledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BillingMonth")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExtraCharges")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExtraDocuments")
                        .HasColumnType("int");

                    b.Property<int>("IncludedDocuments")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StripeInvoiceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SystemStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalCharged")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalDocuments")
                        .HasColumnType("int");

                    b.HasKey("DocumentUsageId");

                    b.HasIndex("SystemStatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("DocumentUsages");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.StaffSyncLog", b =>
                {
                    b.Property<Guid>("StaffSyncLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RecordsAdded")
                        .HasColumnType("int");

                    b.Property<int>("RecordsSynced")
                        .HasColumnType("int");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("int");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SyncCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SyncStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SystemStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StaffSyncLogId");

                    b.HasIndex("SourceTypeId");

                    b.HasIndex("SystemStatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("StaffSyncLogs");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AzureClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AzureTenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BAAExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BAAReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("BAASignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHipaaEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("MailboxAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScanInboxAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SharePointSiteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharePointSiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SystemStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnknownSenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnknownSenderTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasFilter("[Domain] IS NOT NULL");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.TenantConnection", b =>
                {
                    b.Property<Guid>("TenantConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SystemStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantConnectionId");

                    b.HasIndex("SourceTypeId");

                    b.HasIndex("SystemStatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantConnections");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.TenantConnectorConfig", b =>
                {
                    b.Property<Guid>("TenantConnectorConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionString")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("LastTestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderEmailColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderIdColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderNameColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderTableName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderTypeIdColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("StaffDepartmentColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StaffEmailColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StaffIdColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StaffJobTitleColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StaffNameColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StaffTableName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SystemStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantConnectorConfigId");

                    b.HasIndex("SourceTypeId");

                    b.HasIndex("SystemStatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantConnectorConfigs");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.TenantSubscription", b =>
                {
                    b.Property<Guid>("TenantSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DocsPerStaff")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExtraDocumentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IncludedDocuments")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerStaff")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripePlanId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantSubscriptionId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantSubscriptions");
                });

            modelBuilder.Entity("Doario.Data.Models.Lookups.Sender", b =>
                {
                    b.HasOne("Doario.Data.Models.Lookups.SenderType", "SenderType")
                        .WithMany()
                        .HasForeignKey("SenderTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SenderType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.Lookups.SenderType", b =>
                {
                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.Document", b =>
                {
                    b.HasOne("Doario.Data.Models.Lookups.DocumentStatus", "DocumentStatus")
                        .WithMany()
                        .HasForeignKey("DocumentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Lookups.Sender", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Lookups.SenderType", "SenderType")
                        .WithMany()
                        .HasForeignKey("SenderTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Mail.ImportedStaff", "UploadedByStaff")
                        .WithMany()
                        .HasForeignKey("UploadedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentStatus");

                    b.Navigation("Sender");

                    b.Navigation("SenderType");

                    b.Navigation("Tenant");

                    b.Navigation("UploadedByStaff");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.DocumentAssignment", b =>
                {
                    b.HasOne("Doario.Data.Models.Mail.ImportedStaff", "AssignedToStaff")
                        .WithMany()
                        .HasForeignKey("AssignedToStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Lookups.AssignmentType", "AssignmentType")
                        .WithMany()
                        .HasForeignKey("AssignmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Mail.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToStaff");

                    b.Navigation("AssignmentType");

                    b.Navigation("Document");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.DocumentDelivery", b =>
                {
                    b.HasOne("Doario.Data.Models.Mail.DocumentAssignment", "DocumentAssignment")
                        .WithMany()
                        .HasForeignKey("DocumentAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Mail.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Lookups.SystemStatus", "SystemStatus")
                        .WithMany()
                        .HasForeignKey("SystemStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("DocumentAssignment");

                    b.Navigation("SystemStatus");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.DocumentMessage", b =>
                {
                    b.HasOne("Doario.Data.Models.Mail.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Lookups.MessageType", "MessageType")
                        .WithMany()
                        .HasForeignKey("MessageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Mail.ImportedStaff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("MessageType");

                    b.Navigation("Staff");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.ImportedSender", b =>
                {
                    b.HasOne("Doario.Data.Models.Lookups.SenderType", "SenderType")
                        .WithMany()
                        .HasForeignKey("SenderTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Lookups.SourceType", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SenderType");

                    b.Navigation("SourceType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.Mail.ImportedStaff", b =>
                {
                    b.HasOne("Doario.Data.Models.Lookups.SourceType", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.DocumentUsage", b =>
                {
                    b.HasOne("Doario.Data.Models.Lookups.SystemStatus", "SystemStatus")
                        .WithMany()
                        .HasForeignKey("SystemStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SystemStatus");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.StaffSyncLog", b =>
                {
                    b.HasOne("Doario.Data.Models.Lookups.SourceType", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Lookups.SystemStatus", "SystemStatus")
                        .WithMany()
                        .HasForeignKey("SystemStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceType");

                    b.Navigation("SystemStatus");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.TenantConnection", b =>
                {
                    b.HasOne("Doario.Data.Models.Lookups.SourceType", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Lookups.SystemStatus", "SystemStatus")
                        .WithMany()
                        .HasForeignKey("SystemStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany("Connections")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceType");

                    b.Navigation("SystemStatus");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.TenantConnectorConfig", b =>
                {
                    b.HasOne("Doario.Data.Models.Lookups.SourceType", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.Lookups.SystemStatus", "SystemStatus")
                        .WithMany()
                        .HasForeignKey("SystemStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceType");

                    b.Navigation("SystemStatus");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.TenantSubscription", b =>
                {
                    b.HasOne("Doario.Data.Models.SaaS.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Doario.Data.Models.SaaS.Tenant", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
